### ISSUE TITLE
Mechanic Class Trader Still Breaks Inventory Containers

### ISSUE THREAD

**Issue by JaRyCu** [dwallorde/War-of-the-Walkers-Mod-V7#10]
Class trader shaped like a castle.  Mechanic vending machine is the 1st machine to the right side of the class trader.  When I opened the inventory for it, it throws the error in the picture attached and I have to restart the entire 7D game in order to fix it.  Restarting the save doesn't fix it.

I'm using the most current beta as of posting this on March 15, 2020, downloaded manually from the Github here.  I had the same issue in the original beta for a18 last week, and it was marked fixed in the Discord, but it happened again tonight so it's not fixed yet.

![WotW a18 4 Broken Vending Machine](https://user-images.githubusercontent.com/15949393/76712501-0d53c780-66f0-11ea-8bf9-9da3ad86fd3c.JPG)

**Comment by dwallorde** [comment]
Should be Fixed in V7.0.5.  Please allow the restock day to occur in order for the fix to take effect.  But should take effect right away.  Start a new ticket if this occurs with latest update.
