### ISSUE TITLE
Grandpa john issues

### ISSUE THREAD

**Issue by GrandpaJohnGaming** [dwallorde/War-of-the-Walkers-Mod-V7#3]
Opened op a save game after the updated on 14/3:

1. - Still getting 2 painting when hitting 1, I get 1 vanilla and 1 new painting
2. - Basic windows (centered) 3 - not scrappable
3. - Toys still no icon
4. - When opening my map all traders locations disappeared
5. - resource pillars still exist
6. - custom cars half in the ground
7. - Class vending machine in top left side (with Food) not regular ones. value negative error, must     be positive, to to fix you need a full restart of the game.

**Comment by dwallorde** [comment]
Can you confirm any of these are still a thing?  V7.0.3 being released now with a fix for sure for #2.  #5 is intentional. as that is what the Stone Hammer is used for is upgrading.  Stone axe is mainly considered now a primitive axe that comes before scrap Iron

**Comment by Silverblood1776** [comment]
On the vending machine  (mechanic) is the one with the  range error in my world and i have to restart with a new world all of the others work for me

**Comment by GrandpaJohnGaming** [comment]
Hi Dwall, skills are working, I will play around and let you know if anything comes up

**Comment by GrandpaJohnGaming** [comment]
ok 

1- still getting 2 paintings when hitting them. 1 new + 1 vanilla
