### ISSUE TITLE
Items not displaying correctly

### ISSUE THREAD

**Issue by tarasin** [dwallorde/War-of-the-Walkers-Mod-V7#4]
Linux Version of 7dtd. 
Some of the items in game are just one colour
![A18 4_2020-03-09_18-52-30](https://user-images.githubusercontent.com/61993072/76258752-12c29500-624c-11ea-99cd-5f039e5d85b4.jpg)

Heres my log file: 
[output_log__2020-03-09__18-45-27.txt](https://github.com/dwallorde/War-of-the-Walkers-Mod-V7/files/4308986/output_log__2020-03-09__18-45-27.txt)

**Comment by dwallorde** [comment]
V7.0.3 updates all models with new unity engine.  I hope this will fix it for you, but not entirely sure how to fix that for linux users as I have no way of really knowing why it is doing that.

**Comment by tarasin** [comment]
Yes it has fixed it. Thank you.
