### ISSUE TITLE
2nd Beta Update Breaks Skills/Perks Menu

### ISSUE THREAD

**Issue by JaRyCu** [dwallorde/War-of-the-Walkers-Mod-V7#5]
I downloaded the newest beta this morning, posted 12 hours ago tot he Github.  Manual install, Win10 machine.  The game loaded fine, and my saved game loaded fine from the original a18 beta.  When I opened the skills menu, it threw the error in the attached image.  I closed the world, reloaded the world, and got the same error.

![WotW Error Skills Menu](https://user-images.githubusercontent.com/15949393/76432936-047a9300-638a-11ea-9ab7-320a2733d5ae.JPG)

It also causes the skills menu to be offset into the wrong location.  Closing it and opening it a couple of times fixes that issue.

**Comment by bandlbraun** [comment]
Same thing here. It also doesn't allow you to open up any of the other 5 windows, only the default attskills.

**Comment by dwallorde** [comment]
Fixed in V7.0.3 being released now
